# Generated by Django 3.2 on 2021-12-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleOTP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
