# Generated by Django 3.2 on 2021-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleOTP', '0004_auto_20211223_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleotp',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Codigo',
        ),
    ]
