# Generated by Django 3.2 on 2021-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleOTP', '0005_auto_20211223_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funfou', models.BooleanField()),
            ],
        ),
    ]
